# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: getong/mariadb-action@v1.1
      with:
#         host port: 3306 # Optional, default value is 3306. The port of host
#         container port: 3306 # Optional, default value is 3306. The port of container
#         character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
#         collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
#         mariadb version: 'latest' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'dpemr_test' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'password' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'password' # Required if "mysql user" exists. The password for the "mysql user"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install parallel
    - name: Build project
      run:
        cargo build
    - name: Run tests
      run: |
        cd tester
        ./run_tests.sh
